version: '3'

services: 
  api:
      container_name: agenda_marketing_api
      image: node:10-alpine
      networks: 
          - db_networks
      ports: 
          - "3000:3000"
      depends_on: 
          - db
      working_dir: /app
      volumes: 
          - ./:/app
      command: sh -c "npm install && npm run start"
      
  db:
      container_name: agenda_marketing_db
      image: mongo
      ports:
          - "27017:27017"
      volumes: 
          - ./mongo/data:/data/db
      networks: 
          - db_networks
      environment:
        MONGODB_DATABASE: calendar
        MONGODB_USERNAME: root 
        MONGODB_PASSWORD: root

networks: 
    db_networks: